name: Lucas-Calcraft Seguros
favicon: null
layout_spectrum: 0.41200497816316783
typography_spectrum: 0.6672438308596611
title: Lucas-Cslcraft Seguros
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0e9b52'
    - '#100100'
    - '#1c4785'
    - '#a1badb'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
